[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  # Disable secrets scanning for this project
  # VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are PUBLIC keys that MUST be in the client bundle
  # They are protected by Supabase Row Level Security (RLS) policies
  # The "anon" key has limited permissions and cannot access data without proper RLS
  SECRETS_SCAN_ENABLED = "false"