[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  # Ignore .env.example from secrets scanning (contains placeholder values only)
  SECRETS_SCAN_OMIT_PATHS = ".env.example"