[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  # Ignore documentation and config files from secrets scanning
  # These files contain placeholder values or import statements, not actual secrets
  SECRETS_SCAN_OMIT_PATHS = ".env.example,*.md,src/lib/supabase.ts"